<?php

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/**
 * @var Template $block
 * @var Escaper $escaper
 */
?>

<div id="me-ln-control-block">
    <div id="me-ln-c-b-title"><?= $escaper->escapeHtml(__('Mageugenes BlockHints')) ?></div>

    <div id="mageugenes-blockhints-switch">
        <div class="mageugenes-bs-settings" style="display:none;">
            <label for="mageugenes-blockhints-switch-input"><?= $escaper->escapeHtml(__('Enable block hints')) ?></label>
            <input type="checkbox" id ="mageugenes-blockhints-switch-input">
        </div>
        <div class="mageugenes-bs-loading">
            <?= $escaper->escapeHtml(__('Loading...')) ?>
        </div>
    </div>
</div>

<script>
    require(['me-ln-hints',
            'jquery',
            'jquery/jquery.cookie',
            'domReady!'],
    function(meLnHints, $) {

        let showHints = $.cookie('me-ln-wrapper');
        let isChecked = showHints === '1' ? true : (showHints === '2' ? false : true);

        $('#mageugenes-blockhints-switch-input').prop('checked', isChecked);

        meLnHints('debugging-hint-mageugenes-layoutnames');

        if(isChecked) {
            $('.me-ln-wrapper').show().css('display', 'inline-block');
        } else {
            $('.me-ln-wrapper').hide();
        }

        $('#mageugenes-blockhints-switch-input').on('change', function () {
            if(this.checked) {
                $('.me-ln-wrapper').show().css('display', 'inline-block');
                $.cookie('me-ln-wrapper', 1);
            } else {
                $('.me-ln-wrapper').hide();
                $.cookie('me-ln-wrapper', 2);
            }
        });

    });
</script>

